Get devices for measurement successfully!
#### # Linerar 192 4096 16384
/root/siton-data-guoguodata/tcj/brainstorm_project/brainstorm/.cache/log/kernel_tune/NVIDIA_A800_80GB_PCIe/Linear_forward_input_0_192_4096_output_0_192_16384_in_features_4096_out_features_16384.json
/root/siton-data-guoguodata/tcj/brainstorm_project/brainstorm/.cache/log/kernel_tune/NVIDIA_A800_80GB_PCIe/Linear_forward_input_0_192_4096_output_0_192_16384_in_features_4096_out_features_16384.json
#### Find tuned kernel, pass
type(x)<class 'list'>
type(y)<class 'list'>
type(linear.weight)<class 'torch.nn.parameter.Parameter'>
----------------make_jit_kernel@linear_4096.py-----------------
------------make_jit_kernel@factory.py-----------------
objective_func:fastest
-----------------make_kernel@ModuleBase---------------------
---------_make_global_kernel@LinearModule-----------
sample_inputs.shape:torch.Size([192, 4096])
self.module_name:Linear
method:forward
input_infos:{'input_0': [192, 4096]}
output_infos:{'output_0': [192, 16384]}
parameters:{'in_features': 4096, 'out_features': 16384}
objective_func:fastest
-------load_from_db@ModuleKernel--------
identifier:{"device_name": "NVIDIA_A800_80GB_PCIe", "input_infos": {"input_0": [192, 4096]}, "method": "forward", "op_type": "Linear", "output_infos": {"output_0": [192, 16384]}, "parameters": {"in_features": 4096, "out_features": 16384}}
objective_func:fastest
self.platform:CUDA_GPU
self.input_infos:{'input_0': [192, 4096]}
self.output_infos:{'output_0': [192, 16384]}
---------_make_global_kernel@LinearModule-----------
sample_inputs.shape:torch.Size([192, 4096])
self.module_name:Linear
method:forward
input_infos:{'input_0': [192, 4096]}
output_infos:{'output_0': [192, 16384]}
parameters:{'in_features': 4096, 'out_features': 16384}
objective_func:fastest
-------load_from_db@ModuleKernel--------
identifier:{"device_name": "NVIDIA_A800_80GB_PCIe", "input_infos": {"input_0": [192, 4096]}, "method": "forward", "op_type": "Linear", "output_infos": {"output_0": [192, 16384]}, "parameters": {"in_features": 4096, "out_features": 16384}}
objective_func:fastest
self.platform:CUDA_GPU
self.input_infos:{'input_0': [192, 4096]}
self.output_infos:{'output_0': [192, 16384]}
-----------init@HorizFusedKernel-------------
-------------initialize@HorizFusedKernel-------------
self.device_args['placeholder_0, placeholder1_0, T_matmul_NT_0', 'placeholder_1, placeholder1_1, T_matmul_NT_1']
self.shm_sizes[8192]
self.min_blocks_per_sm:1
self.blockidx_x:2048
-----------------get_code@GlobalKernel---------------------
--------------------------------------
processed_template_fname:/root/siton-data-guoguodata/tcj/brainstorm_project/brainstorm/.cache/kernel_template/processed_Linear__in.cu
-------------generate_kernel@CUDACompiler---------------
-------------global@CUDACompiler---------------
kernel_type:horiz_fuse
__ctx__0
----------------execute_kernel@linear_4096.py-----------------
Traceback (most recent call last):
  File "linear_4096_16384.py", line 117, in <module>
    model(x)
  File "/root/siton-data-guoguodata/tcj/brainstorm_project/brainstorm/python/brt/jit/compiler.py", line 22, in func
    jit.static_invoke(inputs, extra, __ctx__)
TypeError: static_invoke(): incompatible function arguments. The following argument types are supported:
    1. (arg0: List[at::Tensor], arg1: List[int], arg2: int) -> None

Invoked with: ([tensor([[ 1.5295,  0.0471,  0.3423,  ..., -0.9108, -0.4894, -0.5474],
        [ 0.0092,  1.0727, -0.3654,  ...,  0.6064, -0.1843, -0.3772],
        [ 1.5887,  0.9692,  1.0528,  ..., -1.2926, -1.0831, -1.2680],
        ...,
        [ 1.1079, -0.3656, -0.5175,  ...,  0.9187,  0.3874,  1.0846],
        [-1.0500, -0.4134,  0.4844,  ..., -0.0763,  0.5711, -0.3760],
        [-0.7938, -0.8213, -0.5891,  ..., -1.7659, -0.2687, -0.0810]],
       device='cuda:0'), tensor([[ 1.5295,  0.0471,  0.3423,  ..., -0.9108, -0.4894, -0.5474],
        [ 0.0092,  1.0727, -0.3654,  ...,  0.6064, -0.1843, -0.3772],
        [ 1.5887,  0.9692,  1.0528,  ..., -1.2926, -1.0831, -1.2680],
        ...,
        [ 1.1079, -0.3656, -0.5175,  ...,  0.9187,  0.3874,  1.0846],
        [-1.0500, -0.4134,  0.4844,  ..., -0.0763,  0.5711, -0.3760],
        [-0.7938, -0.8213, -0.5891,  ..., -1.7659, -0.2687, -0.0810]],
       device='cuda:0')],), [], 0
Exception ignored in: <function LocalRPCMeasureContext.__del__ at 0x7fe6603bba60>
Traceback (most recent call last):
  File "/root/siton-data-guoguodata/tcj/miniconda3/lib/python3.8/site-packages/tvm/auto_scheduler/measure.py", line 588, in __del__
  File "/root/siton-data-guoguodata/tcj/miniconda3/lib/python3.8/site-packages/tvm/rpc/tracker.py", line 468, in terminate
  File "/root/siton-data-guoguodata/tcj/miniconda3/lib/python3.8/site-packages/tvm/rpc/tracker.py", line 455, in _stop_tracker
AttributeError: 'NoneType' object has no attribute 'socket'
Exception ignored in: <function Tracker.__del__ at 0x7fe5bcdc1700>
Traceback (most recent call last):
  File "/root/siton-data-guoguodata/tcj/miniconda3/lib/python3.8/site-packages/tvm/rpc/tracker.py", line 477, in __del__
  File "/root/siton-data-guoguodata/tcj/miniconda3/lib/python3.8/site-packages/tvm/rpc/tracker.py", line 468, in terminate
  File "/root/siton-data-guoguodata/tcj/miniconda3/lib/python3.8/site-packages/tvm/rpc/tracker.py", line 455, in _stop_tracker
AttributeError: 'NoneType' object has no attribute 'socket'
Exception ignored in: <function Server.__del__ at 0x7fe710e2ef70>
Traceback (most recent call last):
  File "/root/siton-data-guoguodata/tcj/miniconda3/lib/python3.8/site-packages/tvm/rpc/server.py", line 493, in __del__
  File "/root/siton-data-guoguodata/tcj/miniconda3/lib/python3.8/site-packages/tvm/rpc/server.py", line 489, in terminate
  File "/root/siton-data-guoguodata/tcj/miniconda3/lib/python3.8/site-packages/tvm/contrib/popen_pool.py", line 137, in kill
  File "/root/siton-data-guoguodata/tcj/miniconda3/lib/python3.8/site-packages/tvm/contrib/popen_pool.py", line 43, in kill_child_processes
ImportError: sys.meta_path is None, Python is likely shutting down
